export const LOAD_KEYS = "LOAD_KEYS"
export const LOAD_RELATIONSHIPS = "LOAD_RELATIONSHIPS"
export const LOAD_FILTERS = "LOAD_FILTERS"
export const LOAD_PHOTOS = "LOAD_PHOTOS"


export const SET_VIEW = "SET_VIEW"
export const SET_PARAMS = "SET_PARAMS"
export const SET_PAGE = "SET_PAGE"

export const INIT_STATUS = "INIT_STATUS"
export const UPDATE_PAGE_STATUS = "UPDATE_PAGE_STATUS"
export const UPDATE_PAGE = "UPDATE_PAGE"
export const LOAD_COLOR_THEMES = "LOAD_COLOR_THEMES"
export const LOAD_PARAMS = "LOAD_PARAMS"
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const UPDATE_AUTH = "UPDATE_AUTH"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
